### PR TITLE
fix: decouple agent piece version from mcp tool naming

### LINKED ISSUE #8311: Show Error When OpenAI Provider Is Not Connected in MCP
MCP actions fail silently if OpenAI provider isn’t connected. Show a clear error message.

### PR DESCRIPTION
**Pull request by hazemadelkhalel**
### Relevant User Scenarios

Fixes #8311

### CODE REVIEW

File: packages/server/api/src/app/mcp/mcp-service.ts [hunk 1]
```diff
@@ -86,7 +87,13 @@ export const mcpService = (_log: FastifyBaseLogger) => ({
         const enrichedTools = await Promise.all(mcp.tools.map((tool) => enrichTool(tool, mcp.projectId, _log))).then(tools => tools.filter(tool => tool !== null))
         return {
             ...mcp,
-            tools: enrichedTools,
+            tools: enrichedTools.map(tool => tool.tool),
+            toolNameMapping: enrichedTools.reduce((acc: Record<string, string>, tool) => {
```
Comment (abuaboud) [inline packages/server/api/src/app/mcp/mcp-service.ts]: This is exposed as public api, calling toolNameMapping is weird, It should be just part of the tool?

File: packages/server/api/src/app/database/migration/common/1751834548223-UpgradeAgentPieceVersion.ts [hunk 2]
```diff
@@ -0,0 +1,171 @@
+import { gt } from 'semver'
```
Comment (abuaboud) [inline packages/server/api/src/app/database/migration/common/1751834548223-UpgradeAgentPieceVersion.ts]: didn't we agree to make something like seed dev?

File: packages/pieces/community/agent/src/lib/agent-executor.ts [hunk 3]
```diff
@@ -119,6 +119,21 @@ function isMarkAsComplete(block: AgentStepBlock): boolean {
     return block.type === ContentBlockType.TOOL_CALL && block.toolName === agentbuiltInToolsNames.markAsComplete
 }
 
+function findActionName(toolName: string, mcp: McpWithTools): string | undefined {
```
Comment (abuaboud) [inline packages/pieces/community/agent/src/lib/agent-executor.ts]: this should not exit, It should be mcp.tools[X].toolName?

File: packages/server/api/src/app/onstart/onstart.service.ts [hunk 4]
```diff
@@ -0,0 +1,7 @@
+import { flowVersionMigrationService } from './flow-version-migration.service'
+
+export const onstartService = {
```
Comment (abuaboud) [inline packages/server/api/src/app/onstart/onstart.service.ts]: overabstraction :P just remove

File: packages/server/api/src/app/onstart/flow-version-migration.service.ts [hunk 5]
```diff
@@ -0,0 +1,29 @@
...
+import { flowVersionRepo } from '../flows/flow-version/flow-version.service'
+import { system } from '../helper/system/system'
+
+const log = system.globalLogger()
+
+export const flowVersionMigrationService = {
+    async migrate() {
+        log.info('Starting flow version migration')
+        let count = 0
+        const flowVersions = await flowVersionRepo().find()
```
Comment (abuaboud) [inline packages/server/api/src/app/onstart/flow-version-migration.service.ts]: I think we should remove the names for the migration and just apply all of them

File: packages/server/api/src/app/onstart/flow-version-migration.service.ts [hunk 6]
```diff
@@ -0,0 +1,29 @@
+import { flowMigrations, FlowVersion } from '@activepieces/shared'
+import { flowVersionRepo } from '../flows/flow-version/flow-version.service'
+import { system } from '../helper/system/system'
+
+const log = system.globalLogger()
+
+export const flowVersionMigrationService = {
+    async migrate() {
+        log.info('Starting flow version migration')
+        let count = 0
```
Comment (abuaboud) [inline packages/server/api/src/app/onstart/flow-version-migration.service.ts]: I think your query should be by schema version, (maybe we should index that :P)

File: packages/server/api/src/app/onstart/flow-version-migration.service.ts [hunk 7]
```diff
@@ -0,0 +1,29 @@
...
+        const flowVersions = await flowVersionRepo().find()
+        const migrationsToApply = ['migrate-v2-agent-piece-to-2.0.0']
+        for (const flowVersion of flowVersions) {
+            const migratedFlowVersion: FlowVersion = flowMigrations.apply(flowVersion, migrationsToApply)
+            if (flowVersion === migratedFlowVersion) {
```
Comment (abuaboud) [inline packages/server/api/src/app/onstart/flow-version-migration.service.ts]: Maybe we can compare schema versions?
