### PR TITLE
fix: reset usage, stop testing from consuming tasks

### LINKED ISSUE #3776: [BUG]: Infinite loading of Runs page
**Describe the bug**
Infinite loading of Runs page: https://cloud.activepieces.com/runs?limit=10

**To Reproduce**
1. Open Runs page
2. Get infinite loading

**Expected behavior**
I see runs of my flows

**Screenshots**
image
image

**Additional context**
Network log shows the next error: 

{
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "userPlatformId and paramId should be equal"
}

### PR DESCRIPTION
**Pull request by Louai-Zokerburg**
## What does this PR do? 

- decrease ai credits threshold to $15
- show the right plan on business trial
- reset usage to reset untill the start of current month
- never increase tasks on test flow and test step

Fixes #3776

### CODE REVIEW

File: packages/server/api/src/app/workers/engine-controller.ts [hunk 1]
```diff
@@ -101,7 +101,7 @@ export const flowEngineWorker: FastifyPluginAsyncTypebox = async (app) => {
         const runWithoutSteps = await flowRunService(request.log).updateRun({
             flowRunId: runId,
             status: runDetails.status,
-            tasks: runDetails.tasks,
+            tasks: progressUpdateType === ProgressUpdateType.TEST_FLOW ? 0 : runDetails.tasks,
```
Comment (AbdulTheActivePiecer) [inline packages/server/api/src/app/workers/engine-controller.ts]: revert this
