### PR TITLE
fix(s3): update trigger strategy to time based for duplicate  file issue

### LINKED ISSUE #7535: [BUG]: S3 "New File" Trigger Fires for Pre-existing Files After Flow is Published
**Describe the bug**
The AWS S3 "New File" trigger activates the flow for pre-existing files upon publishing. It should only fetch files created after the flow's publish timestamp.

### PR DESCRIPTION
**Pull request by kishanprmr**
## What does this PR do?

Fixes #7535

### CODE REVIEW

File: packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts [hunk 1]
```diff
@@ -1,94 +1,105 @@
...
+
+		const s3 = createS3(auth);
+
+		const bucketFiles = [];
+
+		let hasMore = true;
+		let nextToken: string | undefined;
+
+		do {
+			const params: any = {
```
Comment (AbdulTheActivePiecer) [inline packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts]: remove the any

File: packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts [hunk 2]
```diff
@@ -1,94 +1,105 @@
...
+			hasMore = !!response.IsTruncated;
+			nextToken = response.NextContinuationToken ?? undefined;
+
+		} while (hasMore);
+
+		return bucketFiles.map((file) => ({
+			epochMilliSeconds: dayjs(file.LastModified).valueOf(),
+			data: file,
+		}));
+	},
```
Comment (AbdulTheActivePiecer) [inline packages/pieces/community/amazon-s3/src/lib/triggers/new-file.ts:64]: The returned data type previously is different no ? 

`  const currentValues = (await s3.listObjectsV2(params)).Contents ?? [];
    const items = (currentValues as any[]).map((item: { Key: string }) => ({
      id: item.Key,
      data: item,
    }));`
