### PR TITLE
fix: webhook multipart requests

### LINKED ISSUE #2930: Mutlipart Form Data
The convert body function doesn't work with the multipart form.
request.parts() do not return the required result.

Image

### PR DESCRIPTION
**Pull request by khaledmashaly**
## What does this PR do?

* fixes #2930 
* fixes logger level in dev mode

### CODE REVIEW

File: packages/backend/src/app/webhooks/webhook-controller.ts [hunk 1]
```diff
@@ -176,23 +176,17 @@ async function convertRequest(request: FastifyRequest): Promise<EventPayload> {
...
-                const fileBuffer = Buffer.concat(chunks)
-                jsonResult[part.fieldname] = fileBuffer.toString('base64')
-            }
-            else {
-                jsonResult[part.fieldname] = part.value
-            }
+        const requestBodyEntries = Object.entries(request.body as Record<string, unknown>)
+
+        for (const [key, value] of requestBodyEntries) {
+            jsonResult[key] = value instanceof Buffer ? value.toString('base64') : value
```
Comment (abuaboud) [inline packages/backend/src/app/webhooks/webhook-controller.ts:185]: Can we use memory file format, its ugly to expose it from engine but whay do you think?

**Review by abuaboud — DISMISSED** [review]

File: packages/backend/src/app/webhooks/webhook-controller.ts (hunk 1 above)
Comment (khaledmashaly) [reply packages/backend/src/app/webhooks/webhook-controller.ts:185]: will move it to another task
