### PR TITLE
fix: support bracket notation

### LINKED ISSUE #1359: [BUG]: Switch to Bracket notion
**Bug Description**
If a JSON key contains a space or dot, it will cause a bug. To resolve this, we need to switch from using this notation: `trigger.queryParams` to `trigger['queryParams']`.

### PR DESCRIPTION
**Pull request by AbdulTheActivePiecer**
## What does this PR do?

Closes #1359.

### CODE REVIEW

File: packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/utils.ts [hunk 1]
```diff
@@ -10,6 +10,48 @@ import { DomSanitizer } from '@angular/platform-browser';
...
+  }
+
+  return result.map((w) => {
+    if (w.startsWith(`"`) || w.startsWith(`'`)) {
+      return w.slice(1, w.length - 1);
+    }
+    return w;
+  });
+};
+
```
Comment (abuaboud) [inline packages/ui/feature-builder-form-controls/src/lib/interpolating-text-form-control/utils.ts:54]: Replace with

```ts
const keysWithinPath = (path: string) => {
  const result = [];
  let word = '';
  for (let i = 0; i < path.length; i++) {
    const char = path[i];
    if (char === '.' || char === '[' || char === ']') {
      if (word) {
        result.push(word.replace(/^['"]|['"]$/g, ''));
        word = '';
      }
    }
    if (char !== '.' && char !== '[' && char !== ']') {
      word += char;
    }
  }
  if (word) {
    result.push(word.replace(/^['"]|['"]$/g, ''));
  }
  return result;
};
```

**Review by abuaboud — APPROVED** [review]
