### PR TITLE
fix: sandbox error on windows

### LINKED ISSUE #3634: [Windows]: Github auth connection fails in local development
**Describe the bug**
Github auth connection not working in local development (Windows 10 Pro) Build: 19045.3086

**To Reproduce**
1. Clone the repo
2. prepare the dev environment  (via setup-dev.js script)
3. add github to /backend/.env `AP_DEV_PIECES` variable
4. run `npm run start`
5. Visit the frontend in localhost:4200
6. login
7. Create a new flow
8. Select Github as a first step
9. Select "New Issue" as a trigger (or any other option)
10. Create a new github connection and complete the auth steps in the github popup and hit save 
11. Select the connection you just made from the Connections dropdown menu
12. Try to select a repository you'll get the following screen (see attached image)

**Expected behavior**
I should be able to see a list of repositories

**Screenshots**
image

**Additional context**
Here's the error from the terminal:

```
[API] [07:07:48 UTC] ERROR: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dist\packages\pieces\github' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\@activepieces\piece-github'
[API]     reqId: "req-2e"
[API]     req: {
[API]       "method": "POST",
[API]       "url": "/v1/pieces/options",
[API]       "hostname": "localhost:3000",
[API]       "remoteAddress": "127.0.0.1",
[API]       "remotePort": 58109
[API]     }
[API]     res: {
[API]       "statusCode": 500
[API]     }
[API]     err: {
[API]       "type": "Error",
[API]       "message": "EPERM: operation not permitted, symlink 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dist\\packages\\pieces\\github' -> 'C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\@activepieces\\piece-github'",
[API]       "stack":
[API]           Error: EPERM: operation not permitted, symlink 'C:\Users\Zakher\Desktop\coding\activepieces\dist\packages\pieces\github' -> 'C:\Users\Zakher\Desktop\coding\activepieces\dev\cache\sandbox\1\node_modules\@activepieces\piece-github'
[API]       "errno": -4048,
[API]       "code": "EPERM",
[API]       "syscall": "symlink",
[API]       "path": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dist\\packages\\pieces\\github",
[API]       "dest": "C:\\Users\\Zakher\\Desktop\\coding\\activepieces\\dev\\cache\\sandbox\\1\\node_modules\\@activepieces\\piece-github",
[API]       "context": {
[API]         "[SandboxProvisioner#provision]": {
[API]           "pieces": [
[API]             {
[API]               "packageType": "REGISTRY",
[API]               "pieceType": "OFFICIAL",
[API]               "pieceName": "@activepieces/piece-github",
[API]               "pieceVersion": "0.3.4"
[API]             }
[API]           ],
[API]           "codeSteps": [],
[API]           "cacheInfo": {
[API]             "type": "PIECE",
[API]             "pieceName": "@activepieces/piece-github",
[API]             "pieceVersion": "0.3.4"
[API]           }
[API]         }
[API]       }
[API]     }
```

### PR DESCRIPTION
**Pull request by MoShizzle**
## What does this PR do?

Fixes #3634

### CODE REVIEW

File: packages/backend/src/app/workers/sandbox/file-sandbox.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export class FileSandbox extends AbstractSandbox {
         const command = [
             `cd ${this.getSandboxFolderPath()}`,
             '&&',
-            `cross-env-shell AP_PIECES_SOURCE=${pieceSources} NODE_OPTIONS=--enable-source-maps`,
+            `cross-env-shell AP_PIECES_SOURCE=${pieceSources} NODE_OPTIONS=--enable-source-maps ${process.platform === 'win32' ? '&&' : ''}`,
```
Comment (abuaboud) [inline packages/backend/src/app/workers/sandbox/file-sandbox.ts:38]: Windows works in mysterious way, I am curious how && solved it.

Comment (abuaboud) [reply packages/backend/src/app/workers/sandbox/file-sandbox.ts:38]: Do you have to apply it for package.json aliases too?

Comment (MoShizzle) [reply packages/backend/src/app/workers/sandbox/file-sandbox.ts:38]: No npm start works fine, but this is needed here for some reason :D
