### PR TITLE
fix: install piece from registry timing out

### LINKED ISSUE #8587: [BUG]: Installing piece times out
**Describe the bug**
Installing piece times out

**To Reproduce**
Install a piece via the platform admin pieces page via npm or tar

### PR DESCRIPTION
**Pull request by hazemadelkhalel**
## What does this PR do?

Fixes #8587

### CODE REVIEW

File: packages/server/worker/src/lib/runner/index.ts [hunk 1]
```diff
@@ -67,7 +67,14 @@ export const engineRunner = (log: FastifyBaseLogger): EngineRunner => ({
     async extractPieceMetadata(engineToken, operation) {
         log.debug({ operation }, '[threadEngineRunner#extractPieceMetadata]')
 
-        const lockedPiece = await pieceEngineUtil(log).resolveExactVersion(engineToken, operation)
+        let lockedPiece: PiecePackage
+        try {
+            lockedPiece = await pieceEngineUtil(log).resolveExactVersion(engineToken, operation)
+        }
+        catch {
+            lockedPiece = await pieceEngineUtil(log).enrichPieceToInstall(engineToken, operation)
```
Comment (abuaboud) [inline packages/server/worker/src/lib/runner/index.ts]: It's wrong to try something and expect it to throw exception then try to solve it, can we do iit without catch what's the issue there? how is this is related to timeout?

Comment (hazemadelkhalel) [reply packages/server/worker/src/lib/runner/index.ts]: When you try to install a piece, getPiece throws because the piece metadata does not exist yet.

So it keeps stuck because we didn't reply to extractPieceInformation

File: packages/server/worker/src/lib/utils/flow-engine-util.ts [hunk 2]
```diff
@@ -115,4 +141,12 @@ type LockFlowVersionParams = {
 export type BasicPieceInformation = {
     pieceName: string
     pieceVersion: string
+}
+
+export type EnrichPieceWithArchiveParams = {
```
Comment (abuaboud) [inline packages/server/worker/src/lib/utils/flow-engine-util.ts]: Delete this

File: packages/server/worker/src/lib/utils/flow-engine-util.ts [hunk 3]
```diff
@@ -59,6 +59,32 @@ export const pieceEngineUtil = (log: FastifyBaseLogger) => ({
             }
         }
     },
+    async enrichPieceToInstall(engineToken: string, pieceData: EnrichPieceWithArchiveParams): Promise<PiecePackage> {
```
Comment (abuaboud) [inline packages/server/worker/src/lib/utils/flow-engine-util.ts]: Delete this

File: packages/server/worker/src/lib/runner/index.ts (hunk 1 above)
Comment (abuaboud) [reply packages/server/worker/src/lib/runner/index.ts]: Use `enrichPieceWithArchive` and for pieceMetadata the parameter make like that.

```
pieceMetadata: Pick<PieceMetadataModel, 'name' | 'version' | 'packageType' | 'pieceType'>
```

**Review by abuaboud — CHANGES_REQUESTED** [review]

File: packages/server/worker/src/lib/runner/index.ts [hunk 4]
```diff
@@ -67,7 +67,14 @@ export const engineRunner = (log: FastifyBaseLogger): EngineRunner => ({
     async extractPieceMetadata(engineToken, operation) {
         log.debug({ operation }, '[threadEngineRunner#extractPieceMetadata]')
 
-        const lockedPiece = await pieceEngineUtil(log).resolveExactVersion(engineToken, operation)
+        let lockedPiece: PiecePackage
+        try {
```
Comment (abuaboud) [inline packages/server/worker/src/lib/runner/index.ts]: Replace this part with

```
        const lockedPiece = await pieceEngineUtil(log).enrichPieceWithArchive(engineToken, {
            name: operation.pieceName,
            version: operation.pieceVersion,
            packageType: operation.packageType,
            pieceType: operation.pieceType,
        })
        ```

**Review by abuaboud — APPROVED** [review]
