### PR TITLE
fix: persist sidebar state across browser refresh

### LINKED ISSUE #9491: Remember sidebar state in Flow Builder (open/closed preference)
Right now, when I refresh the Flow Builder, the sidebar always opens again even if I closed it before. It’s annoying to close it every single time. The sidebar should remember my last choice (open or closed) and stay that way after refresh.

### PR DESCRIPTION
**Pull request by akramcodez**
## What does this PR do?

The navigation sidebar now remembers whether it was open or closed when you refresh the page, instead of always defaulting to open.

### Explain How the Feature Works

- Add getSidebarStateFromCookie() to read saved sidebar state
- Initialize sidebar with persisted state instead of always defaulting to open
- Maintain existing cookie-saving functionality when state changes
- Ensures sidebar remembers user's last choice (open/closed) after page refresh

### Relevant User Scenarios
https://github.com/user-attachments/assets/799dcd84-5f07-48e4-80de-ea02dab44312

Fixes #9491

### CODE REVIEW

**Comment by akramcodez** [comment]
PTAL @hazemadelkhalel @AbdulTheActivePiecer thanks.

File: packages/react-ui/src/components/ui/sidebar-shadcn.tsx [hunk 1]
```diff
@@ -30,6 +30,19 @@ const SIDEBAR_WIDTH_MOBILE = '18rem';
...
+  const sidebarCookie = cookies.find(cookie => 
+    cookie.trim().startsWith(`${SIDEBAR_COOKIE_NAME}=`)
+  );
+  if (sidebarCookie) {
+    const value = sidebarCookie.split('=')[1];
+    return value === 'true';
+  }
+  return true;
+}
+
```
Comment (AbdulTheActivePiecer) [inline packages/react-ui/src/components/ui/sidebar-shadcn.tsx]: please move this from cookies to localstorage, and add an optional prefix to the key in localstorage that gets taken from the sidebar provider.

i.e const localStorageKeyForSidebarIsOpenState = `${prefix ?? 'default'}_sidebarIsOpen`

**Review by AbdulTheActivePiecer — CHANGES_REQUESTED** [review]

**Comment by akramcodez** [comment]
@AbdulTheActivePiecer PTAL and let me know if there is any issue

File: packages/react-ui/src/components/ui/sidebar-shadcn.tsx [hunk 2]
```diff
@@ -87,10 +100,10 @@ const SidebarProvider = React.forwardRef<
           _setOpen(openState);
         }
 
-        // This sets the cookie to keep the sidebar state.
-        document.cookie = `${SIDEBAR_COOKIE_NAME}=${openState}; path=/; max-age=${SIDEBAR_COOKIE_MAX_AGE}`;
+        // This sets the localStorage to keep the sidebar state.
```
Comment (AbdulTheActivePiecer) [inline packages/react-ui/src/components/ui/sidebar-shadcn.tsx]: please remove this unnecessary comment, and we will merge it :D 

Comments should always be used to answer "Why" not "What" a piece of code is doing.

**Comment by akramcodez** [comment]
@AbdulTheActivePiecer removed comment

**Comment by AbdulTheActivePiecer** [comment]
@allcontributors please add @akramcodez  for code

**Comment by AbdulTheActivePiecer** [comment]
Ci ran on https://github.com/activepieces/activepieces/pull/9664
